### ISSUE TITLE
API?!

### ISSUE THREAD

**Issue by UnixCro** [aimadnet/tiktok-api-get-followers#1]
I don't understand about the API, what exactly should I do now and why is the program not fully developed yet?

**Comment by aimadnet** [comment]
The script is using scraptik.com API.

You need to get API key from Scraptik.com

**Comment by UnixCro** [comment]
How exactly do I do that?  Can't you just build one into the script?

**Comment by aimadnet** [comment]
Because it's limited to 50 API requests a month (free basic plan)

**Comment by UnixCro** [comment]
Now it makes sense.  Bro when I click on the link it is full of code and confusing.  What exactly do I have to click on the page?

**Comment by aimadnet** [comment]
Go to https://rapidapi.com/contact-cmWXEDTql/api/scraptik/pricing
under "Basic" click "Subscribe" then create a rapidapi account.

**Comment by UnixCro** [comment]
I logged in like your instructions.  When I wanted to subscribe to 0.00, they still wanted my payment methods, so I canceled the process.  I went to My APIs.  I hope I'm right here.  What should I enter here if so?

![F90D42BA-005A-4CC6-99BB-926DD3C1DDF3](https://user-images.githubusercontent.com/70098046/148656108-95f4616a-f7b3-44a6-9735-9da753961b4f.png)

**Comment by UnixCro** [comment]
If you can help me so that I can go live I'll donate $ 5 in Bitcoin

**Comment by Aomayan24** [comment]
did u do it yet

**Comment by UnixCro** [comment]
No, don't use this shit. Use tiktok-bot from a other github Developer
